# CodeSandbox supports debian & ubuntu based images
FROM debian 
# ubuntu

# Example; install htop by default
RUN apt update -y && apt install -y python3-selenium snapd

WORKDIR /
# RUN curl -OL https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
# RUN tar -xzf geckodriver-v0.33.0-linux64.tar.gz
# RUN mv geckodriver /usr/bin/ && rm geckodriver-v0.33.0-linux64.tar.gz




# The project will be mounted in /workspace by default

# Every new shell will open inside the built container

# On top of this build, we install `zsh`, `git` and `docker` as additional
# Docker layers.

